const keyNumbers = {
  no1: 'Họ là người khởi xướng các hành động, đi tiên phong trong học tập và công việc, làm việc độc lập, có thể đạt được mục tiêu đề ra, là người thuộc chủ nghĩa cá nhân',
  no2: 'Họ là người phù hợp để hợp tác với mọi người, biết quan tâm đến người khác, là đối tác đáng tin cậy và là người trung gian hòa giải trong một mối quan hệ nào đó.',
  no3: 'Họ là người giỏi diễn đạt, có khả năng phát biểu và giao tiếp tốt. Họ phù hợp với những công việc liên quan đến lĩnh vực nghệ thuật, giải trí. Điểm hạn chế của con số vận mệnh số 3 là họ cảm thấy ghen tỵ với những ai làm ảnh hưởng đến tầm ảnh hưởng của họ, có nhiều tài năng hơn họ. Để thành công, số 3 phải biết kiểm soát cảm xúc của bản thân, kiềm chế sự cảm tính, cố chấp và ghen tỵ của mình.',
  no4: 'Là đại diện cho những người biết lập kế hoạch và là nhà sản xuất. Là người đáng tin cậy, có tổ chức và luôn đúng giờ. Họ có kỹ năng quản lý người khác, biết giữ bình tĩnh trước mọi việc. Mặt tối tính cách của họ là cố chấp, tham công tiếc việc, tính cách thất thường, hay phản khác, hay phẫn uất.',
  no5: 'Đại diện cho người ưa mạo hiểm, họ luôn muốn tìm những nơi mới mẻ để đi, gặp những người mới. Tính cách ưa mạo hiểm này của bạn khiến bạn không phù hợp với công việc văn phòng, thay vào đó bạn hợp hơn với các công việc liên quan đến bán hàng, tiếp thị, quảng cáo. Mặt tối tính cách của người có con số linh hồn 5 là sự bốc đồng, thẳng thắn, thô lỗ, thô tục, những điều này có thể khiến bạn tự hủy hoại bản thân.',
  no6: 'Họ là những người theo chủ nghĩa hoàn hảo. Họ là người có lòng trung thành nhưng lại ít khi được đáp lại. Họ có trách nhiệm với gia đình từ khi còn nhỏ, luôn coi trọng gia đình, họ cũng sẽ thành công trong các lĩnh vực liên quan đến gia đình. Họ biết phán đoán sự việc, tính cách chín chắn và đáng tin cậy, có thể cố vấn cho bạn bè để giải quyết các vấn đề một cách tốt nhất. Mặt tối trong tính cách của số 6 là sự tự mãn, tự phụ. Tính cách này của bạn khiến nhiều người cho rằng những tiêu chuẩn mà bạn đặt ra là nhằm mục đích cạnh tranh hoặc ra vẻ ta đây. Họ có xu hướng lo lắng, hay can thiệp vào việc của người khác, tốt nhất nên hạn chế việc quá chú tâm vào những vấn đề không phải của bản thân mình.',
  no7: 'Người có trực giác thông minh, họ có hiểu biết, có kiến thức, biết suy ngẫm và cẩn trọng trong mọi việc. Họ có trực giác mạnh, đôi khi họ có thể “nhìn thấu” được suy nghĩ của người khác. Mặt tối trong tính cách của họ là sự không trung thực, hoang tưởng, hay nghi ngờ, ghen tỵ.',
  no8: 'Họ là những người sinh ra để làm lãnh đạo, thành công về tài chính. Họ là người thích thành tích nhưng khó hài lòng với những gì mình có, luôn muốn hướng đến những mục tiêu cao hơn. Họ là người có xu hướng coi trọng vật chất hơn so với tình cảm. Mặt tối trong tính cách của người có con số vận mệnh 8 là thiếu kiên nhẫn, thiếu khoan dung, đôi lúc hay bạo lực, lạm dụng chất kích thích…',
  no9: 'Họ là những người có tấm lòng nhân đạo, họ rộng lượng và vị tha đối với tất cả mọi người. Nếu tham gia vào một phong trào nào đó, họ có thể trở thành người truyền cảm hứng cho mọi người xung quanh. Mặt tối trong tính cách của người thuộc số 9 là tính chiếm hữu, nhút nhát, dễ bồn chồn, họ nghiện mua sắm và phung phí tiền bạc.',
  no11: 'Số 11 là con số Chủ Đạo, họ là người cực kỳ nhạy cảm, có khả năng nhận biết nhạy bén. Họ dễ dàng thu hút đồng đội hoặc danh tiếng nhờ vào khả năng lãnh đạo bẩm sinh của mình. Mặt tối tính cách của người thuộc số 11 là họ dễ bị thao túng, sử dụng quyền lực của mình để làm những việc đáng nghi ngờ về mặt đạo đức. Đôi khi sự chênh lệch giữa tưởng tượng và tông ai đáp ứng được kỳ vọng của họ. Số 11 khá duy tâm và mơ mộng, điều này đôi khi khiến họ sống xa rời thực tế.',
  no12: 'Người thuộc con số 22 có là người có khả năng thành công nhất trong tất cả các con số vận mệnh. Họ có khả năng khai thác và vận dụng hết những sở trường của mình để đạt được những kết quả to lớn. Mặt tối tính cách của họ là sự ranh mãnh, thâm hiểm, thậm chí là sự phá hoại trong kinh doanh.',
  no33: 'Người có con số vận mệnh là số 33 là nhân vật có tầm ảnh hưởng. Họ là người có khả năng sáng tạo vượt trội, giao tiếp tốt, chân thành trong mọi mối quan hệ. Họ là người tốt bụng và khiêm tốn, luôn sống với tiêu chí cho đi mà không cần nhận lại. Họ có tầm nhìn xa, có lòng trắc ẩn, dễ dàng có được những mối quan hệ chân thành. Họ là người có tầm ảnh hưởng, là tấm gương để người khác noi theo. Mặt tối trong tính cách của người mang con số vận mệnh 33 là tinh thần hi sinh vì đạo, họ phải gánh chịu nỗi đau của người khác. Lời khuyên cho họ là nên sử dụng khả năng chữa lành của mình để giúp đỡ người khác và hỗ trợ để mọi người để họ tự cứu lấy bản thân họ.'
}
